version: "3"
services:
  server:
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    image: bedreforslag
    environment:
      - MONGODB_URI=mongodb://database
    depends_on:
      - database
    ports:
      - "3000:80"
    volumes:
      - ./src:/usr/src/app/src
    working_dir: /usr/src/app
    command: sh -c "npm run update:db && npm start"

  database:
    image: mongo:5
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - "27017:27017"
    volumes:
      - db-storage:/data/db
    command: mongod

volumes:
  db-storage:
