version: '3'
services:

  server:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    image: bedreforslag
    env_file: .env
    environment:
      - MONGODB_URI
    depends_on:
      - database
    ports:
      - "80:80"
    volumes:
      - ./src:/usr/src/app/src
    command: sh -c "cd /usr/src/app && npm run update:db && npm run start:dev"

  database:
    image: mongo:4
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - "27017:27017"
    volumes:
      - db-storage:/data/db
    command: mongod --smallfiles

volumes:
  db-storage: